### ISSUE TITLE
Crash on sending to Toolbox in compiled VSIX

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#110]
**Describe the bug**

Using a built and installed VSIX, send something to the Toolbox.
An error is reported. VS may also crash.

```
[12:41:41.200]  Exception
[12:41:41.200]  =========
[12:41:41.232]  Parameter is not valid.
[12:41:41.254]  System.Drawing
[12:41:41.254]     at System.Drawing.Bitmap..ctor(String filename)
   at RapidXamlToolkit.Commands.SendToToolboxCommand.<AddToToolboxAsync>d__7.MoveNext() in E:\Agent\_work\33\s\RapidXAML.VSIX\RapidXamlToolkit\Commands\SendToToolboxCommand.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RapidXamlToolkit.Commands.SendToToolboxCommand.<Execute>d__8.MoveNext() in E:\Agent\_work\33\s\RapidXAML.VSIX\RapidXamlToolkit\Commands\SendToToolboxCommand.cs:line 81
```

**Comment by mrlacey** [comment]
Seems to be a relative path issue.

**Comment by mrlacey** [comment]
The same issue also appears to be affecting the loading of the config file in the latest build (after merging #107)

**Comment by mrlacey** [comment]
Close when verified with via the CI build

**Comment by mrlacey** [comment]
Verified in dev CI build
