### ISSUE TITLE
Bug: Illegal characters in path in VisualStudioAbstraction.GetProjectType

### ISSUE THREAD

**Issue by maxkatz6** [mrlacey/Rapid-XAML-Toolkit#287]
**Describe the bug**
Extension can't parse files in specific projects.

**To Reproduce**
1. Create project named A (powered with MSBuild.Sdk.Extras)
2. In classic UWP project B reference project A
3. In wapproj project (packaging project) reference project B
4. Open xaml file in project A

**Expected behavior**
Extension works normally.

**Additional context**
I have debugged extension and found, that 'otherProj.UniqueName' in GetProjectTypeOfReferencingProject local method can be equal to ```<MiscFiles>``` (it seems like WAPproj has some specific internal references). Path.GetExtension can't parse it, so it throws exception. After adding try-catch code, issue was fixed for me. I don't think, that it is the best solution, however I don't know project well.

Log output:
```
[20:33:36.301]  Illegal characters in path.
[20:33:36.302]  mscorlib
[20:33:36.302]     at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetExtension(String path)
   at RapidXamlToolkit.VisualStudioIntegration.VisualStudioAbstraction.<GetProjectType>g__GetProjectTypeOfReferencingProject|5_3(Project proj, <>c__DisplayClass5_0& ) in F:\wtsb4\_work\12\s\VSIX\RapidXamlToolkit\VisualStudioIntegration\VisualStudioAbstraction.cs:line 95
   at RapidXamlToolkit.VisualStudioIntegration.VisualStudioAbstraction.GetProjectType(Project project) in F:\wtsb4\_work\12\s\VSIX\RapidXamlToolkit\VisualStudioIntegration\VisualStudioAbstraction.cs:line 183
   at RapidXamlToolkit.VisualStudioIntegration.VisualStudioAbstraction.<GetProjectType>g__GetProjectTypeOfReferencingProject|5_3(Project proj, <>c__DisplayClass5_0& ) in F:\wtsb4\_work\12\s\VSIX\RapidXamlToolkit\VisualStudioIntegration\VisualStudioAbstraction.cs:line 125
   at RapidXamlToolkit.VisualStudioIntegration.VisualStudioAbstraction.GetProjectType(Project project) in F:\wtsb4\_work\12\s\VSIX\RapidXamlToolkit\VisualStudioIntegration\VisualStudioAbstraction.cs:line 183
   at RapidXamlToolkit.XamlAnalysis.RapidXamlDocument.Create(ITextSnapshot snapshot, String fileName, IVisualStudioAbstraction vsa) in F:\wtsb4\_work\12\s\VSIX\RapidXamlToolkit\XamlAnalysis\RapidXamlDocument.cs:line 57
```

**Comment by mrlacey** [comment]
Nice find. :)
I'll get a fix in an updated preview release tomorrow.

**Comment by maxkatz6** [comment]
@mrlacey 
Note that markdown parser ate '<', '>' in my previous message in place, where I put value of UniqueName.
I have updated message. Exception was founded with ```UniqueName == "<MiscFiles>"```

**Comment by mrlacey** [comment]
@Tirraon thank you so much for taking the time to report this. 
A fix for this was included in preview version 0.3.11  which was released to the marketplace earlier today.
If the issue still occurs for you with this new version, please let me know. Or get in touch if you have any other problems or suggestions.

**Comment by maxkatz6** [comment]
@mrlacey 
Thanks! I will take a look and close issue at this weekends.

**Comment by maxkatz6** [comment]
It works!
