### ISSUE TITLE
BUG: Null Ref Exception

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#313]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RapidXamlToolkit.XamlAnalysis.Tags.RapidXamlDisplayedTag.TryGetConfiguredErrorType(String errorCode, TagErrorType&amp; tagErrorType) 
in C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\XamlAnalysis\Tags\RapidXamlDisplayedTag.cs:line 122
   at RapidXamlToolkit.XamlAnalysis.Tags.RapidXamlDisplayedTag.get_ConfiguredErrorType() 
in C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\XamlAnalysis\Tags\RapidXamlDisplayedTag.cs:line 57
   at RapidXamlToolkit.XamlAnalysis.RapidXamlDocumentCache.&lt;&gt;c.&lt;AdornmentTags&gt;b__11_0(IRapidXamlAdornmentTag t) 
in C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\XamlAnalysis\RapidXamlDocumentCache.cs:line 131
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at RapidXamlToolkit.XamlAnalysis.RapidXamlDocumentCache.AdornmentTags(String fileName) 
in C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\XamlAnalysis\RapidXamlDocumentCache.cs:line 131
   at RapidXamlToolkit.XamlAnalysis.RapidXamlTagger.&lt;GetTags&gt;d__6.MoveNext() 
in C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\XamlAnalysis\RapidXamlTagger.cs:line 35
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__47.MoveNext()
```

**Describe the bug**
Encountered while experimenting with MVX on UWP

**Comment by mrlacey** [comment]
No repro and line numbers don't help after project refactoring.
Can reopen when hit this again.
