### ISSUE TITLE
RoslynAnalyzer error

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#333]
**v0.9**

```
Analyzer 'RapidXamlToolkit.RoslynAnalyzers.CsExpandAutoPropertiesAnalyzer' threw an exception of type 'System.TypeInitializationException' with message 'The type initializer for 'RapidXamlToolkit.RoslynAnalyzers.CsExpandAutoPropertiesAnalyzer' threw an exception.'.

'RapidXamlToolkit.RoslynAnalyzers.CsExpandAutoPropertiesAnalyzer' threw the following exception:
'System.TypeInitializationException: The type initializer for 'RapidXamlToolkit.RoslynAnalyzers.CsExpandAutoPropertiesAnalyzer' threw an exception. ---> System.MissingMethodException: Method not found: 'System.String RapidXamlToolkit.Resources.StringRes.get_RapidXamlToolkit()'.
   at RapidXamlToolkit.RoslynAnalyzers.CsExpandAutoPropertiesAnalyzer..cctor()
   --- End of inner exception stack trace ---
   at RapidXamlToolkit.RoslynAnalyzers.CsExpandAutoPropertiesAnalyzer.get_SupportedDiagnostics()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.<>c__DisplayClass20_0.<ComputeDiagnosticDescriptors>b__0(Object _)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
System.MissingMethodException: Method not found: 'System.String RapidXamlToolkit.Resources.StringRes.get_RapidXamlToolkit()'.
   at RapidXamlToolkit.RoslynAnalyzers.CsExpandAutoPropertiesAnalyzer..cctor()
-----
'.
```

**Comment by mrlacey** [comment]
cannot repro in 0.9.1
