### ISSUE TITLE
Unable to load custom analyzers

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#334]
**v0.9**

```
[21:51:29.550]  "Failed to load 'C:\Users\matt\source\repos\PersonAnalyzer\DemoUwpApp\bin\x86\Debug\PersonAnalyzer.dll' to look for CustomAnalyzers."
[21:51:29.555]  System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at RapidXamlToolkit.XamlAnalysis.RapidXamlDocument.GetCustomAnalyzers(String dllPath)
[21:51:29.555]  mscorlib
```

**Comment by mrlacey** [comment]
This was done as part of #342
