### ISSUE TITLE
restore NuGet packages for Custom Analysis Projects

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#357]
When adding a new Custom Analysis project (& test project) the NuGet packages referenced by those projects aren't automatically restored.

They should be.

This already happens if adding a single item.

**Comment by mrlacey** [comment]
It turns out this is a known issue with the Project system not correctly restoring NuGet packages for SDK-style projects if they're not already cached locally.
This may be an issue for anyone creating their first custom analyzer. Anyone in this situation will need to manually do a package restore and then all should be good.

Details at: https://github.com/microsoft/VSProjectSystem/issues/221 and https://github.com/microsoft/VSProjectSystem/issues/221


Investigation notes:

Tried using the same approach as ServiceStack https://github.com/ServiceStack/ServiceStackVS/blob/master/src/ServiceStackVS.NuGetInstallerWizard/NuGetPackageInstallerWizard.cs#L30 but get the error:

```ascii
System.InvalidOperationException: The operation failed as details for project MyXamlAnalyzers9 could not be loaded.
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetAssetsFilePathAsync(Boolean shouldThrow)
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.<GetAssetsFilePathAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewBuildIntegratedProjectActionsAsync>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalCoreAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.VsPackageInstaller.RunJTFWithCorrectContext(Project project, Func`1 asyncTask)
   at NuGet.VisualStudio.VsPackageInstaller.InstallLatestPackage(String source, Project project, String packageId, Boolean includePrerelease, Boolean ignoreDependencies)
   at RapidXaml.NugetRestoreWizard.MultiProjectNugetRestoreWizard.ProjectFinishedGenerating(Project project)
```

It shouldn't be necessary to do this, just keep the PackageReference details in the csproj files and all _should_ be fine..
