### ISSUE TITLE
Installation Failed: RelativeUri Error

### ISSUE THREAD

**Issue by LanceMcCarthy** [mrlacey/Rapid-XAML-Toolkit#59]
**Issue**
Installation fails for VS2017 15.6.7

**To Reproduce**
1. Run VSIX generated by the project (in /bin/debug)

![image](https://user-images.githubusercontent.com/3520532/39645063-1429b452-4fa5-11e8-8261-93b0a2102ae5.png)

**Expected behavior**
Successful installation

**Environment**
 - Visual Studio Version: Visual Studio 2017 15.6.7
 - Extension Version: (not sure where to find this)

**Additional context**

Here's the install log file:

[VSIXInstaller_8af6d7ef-f386-4345-9e44-29658d092bb0.log](https://github.com/Microsoft/Rapid-XAML-Toolkit/files/1975453/VSIXInstaller_8af6d7ef-f386-4345-9e44-29658d092bb0.log)

Here's the end of the log:

```
5/4/2018 2:07:32 PM - System.UriFormatException: A relative URI cannot be created because the 'uriString' parameter represents an absolute URI.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionHeaderImpl.get_License()
   at VSIXInstaller.ViewModel.ExtensionViewModel..ctor(IExtension extension, IEnumerable`1 packages, Boolean showPackages)
   at VSIXInstaller.ViewModel.InstallableExtensionViewModel..ctor(IInstallableExtension extension, IEnumerable`1 packages, Boolean showPackages, NotInstallableReason notInstallableReason)
   at VSIXInstaller.ViewModel.InstallableExtensionViewModel.CreateWithoutPackages(InstallExtensionData installData)
   at VSIXInstaller.SingleInstallPage..ctor(ExtensionData data, InstallExtensionData installData, IEnumerable`1 targetSkus)
   at VSIXInstaller.LoadingPage.<>c__DisplayClass11_1.<OnLoaded>b__2()

```

**Comment by mrlacey** [comment]
Based on the call stack, it looks to be because the license specified in `source.extension.vsixmanifest` is an absolute uri to the website when it should be a relative path to a file in the project.

**Comment by mrlacey** [comment]
@LanceMcCarthy delete the license entry from the manifest and you'll be unblocked.
![image](https://user-images.githubusercontent.com/189547/39659226-d2a77e84-501b-11e8-93c6-6a5c6bcb53d0.png)

I'll set this to the proper, relative, uri shortly.

**Comment by mrlacey** [comment]
Will verify and close this when we have the first public VSIX ready

**Comment by mrlacey** [comment]
Verified.
Closing now to tidy up
